# Generated by Django 3.2.8 on 2021-11-09 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fromUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='chat.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='toUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5d99a23-2cc5-4d43-a9de-db4ce8d99d50'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='imageUrl',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('20d7d5cc-8eb2-4856-ab7e-0a3bd7a6d55d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
