# Generated by Django 3.2.8 on 2021-11-09 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211109_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5030c96e-94ed-48be-83c2-99aa4b88bcaf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('234ab267-2ef5-40ea-9d18-94039b165e7f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
