# Generated by Django 3.2.8 on 2021-11-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211118_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='message',
            name='toUser',
        ),
        migrations.AlterField(
            model_name='message',
            name='fromUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.user'),
        ),
    ]
