# Generated by Django 3.2.8 on 2021-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20211123_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imageUrl',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
