# Generated by Django 3.2.8 on 2021-11-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
